# Generated by Django 5.0.4 on 2024-04-20 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OpenPositions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openposition',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='openposition',
            name='longitude',
        ),
    ]
